- lib/derivative_rodeo/services/convert_uri_via_template_service.rb
- lib/derivative_rodeo/storage_targets/base_target.rb
- lib/derivative_rodeo/storage_targets/sqs_target.rb
- spec/derivative_rodeo/storage_targets/sqs_target_spec.rb
previously the params template would get filled in by the regexp. we want to preserve its templatyness. Also we want to preserver  the file path in the tmp dir. We need it for other steps.
> Preserve Template and File Path

- lib/derivative_rodeo/generators/hocr_generator.rb
- lib/derivative_rodeo/generators/pdf_split_generator.rb
- lib/derivative_rodeo/services/convert_uri_via_template_service.rb
- lib/derivative_rodeo/services/pdf_splitter/base.rb
- lib/derivative_rodeo/storage_targets/base_target.rb
- lib/derivative_rodeo/storage_targets/sqs_target.rb
- spec/derivative_rodeo/generators/hocr_generator_spec.rb
- spec/derivative_rodeo/storage_targets/sqs_target_spec.rb
`TMPDIR/path/MyFile.pdf` becomes `TMPDIR/path/MyFile-page1.pdf`. 
Also page count starts at 1 not 0.
> preserve path and filename when splitting pdfs

- lib/derivative_rodeo/generators/base_generator.rb
- spec/derivative_rodeo/generators/base_generator_spec.rb
In the SpaceStone implementation, I'm noticing that we sometimes have multiple URIs and other times singular.  By favoring the `Array.wrap` we're accepting either one and casting them to an Array.
> ♻️ Allowing input_uris to be singular

- lib/derivative_rodeo/generators/thumbnail_generator.rb
- spec/derivative_rodeo/generators/thumbnail_generator_spec.rb
This commit introduces the skeleton of the thumbnail generation necessary for PDFs, images, and the images that we make from the PDFs.
It does not have the full business logic to perform this work; but the specs are mostly in place and can then be used to drive development.
Related to #22
- https://github.com/scientist-softserv/derivative_rodeo/issues/22
> 🎁 WIP - Adding Thumbnail Generator skeleton

- Gemfile.lock
- derivative_rodeo.gemspec
- lib/derivative_rodeo/storage_locations/concerns/download_concern.rb
> Many versions of Valkyrie and ActiveFedora have Faraday `~> 0.9` type
> dependencies whereas the Faraday redirect middleware requires Faraday
> `~> 1.0` or some such thing.
Updating Valkyrie and ActiveFedora's different branches and versions to later Faraday versions.
Closes #31
- https://github.com/scientist-softserv/derivative_rodeo/issues/31
> ♻️ Replacing Faraday with Httparty

- lib/derivative_rodeo.rb
- lib/derivative_rodeo/generators/pdf_split_generator.rb
- lib/derivative_rodeo/services/pdf_splitter/base.rb
- spec/derivative_rodeo/generators/pdf_split_generator_spec.rb
- spec/derivative_rodeo/services/pdf_splitter/base_spec.rb
- spec/derivative_rodeo_spec.rb
As part of working on #219, I was looking into "What is the pathing convention for the split images?"  As I was reading the code to get to that answer, I realized that I wanted to see that information in the `DerivativeRodeo::Generators::PdfSplitGenerator`.
Further, given that the PdfSplitGenerator is part of the more visible "interface" of the DerivativeRodeo, I think it is important for the filename to be present.
Thus I moved towards this refactor, to better expose that and remove additional chatter in the code.  There are still a few things remaining but this has helped re-inforce my understanding of the PDF Splitting.
I could further "compress" the basename template concept into the fully qualitified filename; but I think that would confuse concepts.
Related to:
- …
> ♻️ Improving Legibility of PDF Splitting

- lib/derivative_rodeo/generators/alto_generator.rb
- lib/derivative_rodeo/services/extract_word_coordinates_from_hocr_sgml_service.rb
- spec/derivative_rodeo/generators/alto_generator_spec.rb
This commit will add an Alto XML generator that uses the HOCR file.  In the spec, we check if the XML is well-formed with nokogiri.
- Ref: https://github.com/scientist-softserv/derivative_rodeo/issues/28
> 🎁 Add Alto generator

- lib/derivative_rodeo/storage_locations/concerns/download_concern.rb
The prior implementation was copied from the dash rodeo, which leveraged Httparty and had a different interface.  The reason for the copy is that we previously used Faraday, but had version conflicts.
Related to:
- https://github.com/scientist-softserv/derivative_rodeo/pull/32
> 🐛 Fixing the DownloadConcern to match location interface

- lib/derivative_rodeo/generators/thumbnail_generator.rb
- spec/derivative_rodeo/generators/thumbnail_generator_spec.rb
With this commit, I'm introducing the most barebones and naive functionality for allowing for configurability by type.  This gets us unblocked for scientist-softserv/adventist-dl#330; there's certainly improvements we can make.  But we won't know those until we work through additional DerivativeRodeo client needs.
Closes: #30
Related to:
- https://github.com/scientist-softserv/derivative_rodeo/issues/30
- https://github.com/scientist-softserv/adventist-dl/issues/330
> 🎁 Adding naive configurability for thumbnail dimensions

- lib/derivative_rodeo/generators/pdf_split_generator.rb
- spec/derivative_rodeo/generators/pdf_split_generator_spec.rb
As I'm working on IIIF print and how to detect a split, I want a bit
more options for detecting that split.
This should provide adequate options.
Without this feature, we're asking downstream implementations to answer
if this was a split file or not.
There's still some assumptions but this helps clarify and reduce
assumptions that downstream implementations need make.
> 🎁 Exposing a method to answer "was this a split file" 

- Gemfile.lock
- lib/derivative_rodeo/version.rb
This change brings a few underlying public methods for downstream to use.
Why the minor version?  Any changes prior to 1.0 are volatile and versions don't quite matter.
> ⚙️ Bumping to version 0.3.0

- lib/derivative_rodeo/generators/base_generator.rb
- lib/derivative_rodeo/generators/pdf_split_generator.rb
- lib/derivative_rodeo/storage_locations/base_location.rb
- lib/derivative_rodeo/storage_locations/file_location.rb
- lib/derivative_rodeo/storage_locations/s3_location.rb
- spec/derivative_rodeo/generators/pdf_split_generator_spec.rb
- spec/derivative_rodeo/storage_locations/file_location_spec.rb
- spec/derivative_rodeo/storage_locations/s3_location_spec.rb
Yes, it would be nice to have sub-directories for pages ripped from a PDF.  However, that aspirational state creates complications on the implementation details of the DerivativeRodeo; by moving from a tail glob to a regular expression, we create a more powerful mechanism for finding files.
These changes also highlighted a few implementation bugs (namely ensuring the correct expected return value of the newly re-named function).
In IIIF Print we still need to consider how to find the child page's derivatives of an original PDF.  That is, however, not a problem for this repository.
Related to:
- https://github.com/scientist-softserv/iiif_print/issues/251
> ♻️ Flattening assumptive dir structure for PDFs

- lib/derivative_rodeo/generators/base_generator.rb
- lib/derivative_rodeo/services/convert_uri_via_template_service.rb
- lib/derivative_rodeo/storage_locations/base_location.rb
- lib/derivative_rodeo/storage_locations/sqs_location.rb
- spec/derivative_rodeo/services/convert_uri_via_template_service_spec.rb
Prior to this commit, we did not account for a generator having a stake in the output URI; that is the extension specified in the generator.
The behavior we saw was that our lambdas completed successfully for the split PDF, OCR, etc.  However, the returned URIs were not the derivative file (e.g. `filename--page-1.thumbnail.jpeg`) but were instead the input file (e.g. `filename--page-1.tiff`) repeated back as output.
With this change, the output and pre-processed template can use the suggested output extension of the generator.
Note: there are probably bugs for cases of SAME extension.  We'll work around that.
> 🐛 Exposing means for generator to specify output extension

- lib/derivative_rodeo/services/convert_uri_via_template_service.rb
- spec/derivative_rodeo/services/convert_uri_via_template_service_spec.rb
Prior to this commit, we were seeing "filename.same" in SpaceStone deploys; that's not a likely extension but instead reflects our "same" convention, namely the output extension of a derivative is the same as the given input.
> 🐛 Handling "SAME" output extension for templates

- lib/derivative_rodeo/generators/monochrome_generator.rb
- lib/derivative_rodeo/services/convert_uri_via_template_service.rb
- lib/derivative_rodeo/storage_locations/base_location.rb
- spec/derivative_rodeo/services/convert_uri_via_template_service_spec.rb
Given the "20121816.ARCHIVAL--page-3.tiff" page, prior to this commit we were generating the following files:
- 20121816.ARCHIVAL--page-3.mono.alto.xml
- 20121816.ARCHIVAL--page-3.mono.coordinates.json
- 20121816.ARCHIVAL--page-3.mono.hocr
- 20121816.ARCHIVAL--page-3.mono.plain_text.txt
- 20121816.ARCHIVAL--page-3.mono.tiff
- 20121816.ARCHIVAL--page-3.thumbnail.jpeg
Iiif Print finds the derived files for "20121816.ARCHIVAL--page-3.tiff" by looking for the basename (e.g. "20121816.ARCHIVAL--page-3") and then the generator's output extension (e.g. 'plain_text.txt', 'coordinates.json', etc.)
With this change we chop out the ".mono" out of the locations and should see the following:
- 20121816.ARCHIVAL--page-3.alto.xml
- 20121816.ARCHIVAL--page-3.coordinates.json
- …
> 🐛 Hacking away the .mono suffix for 2nd order derivatives

- lib/derivative_rodeo/generators/base_generator.rb
In reviewing the logs in SpaceStone, I can tell which handler was running based on the lambda's name.  However that does not directly map to the Derivative Rodeo generator.
In otherwords, prior to this commit the logging was not providing the context of the generator.
With this commit, we're including that information as a means of helping debug and triage.
> 🎁 Updating logging to include class name

- lib/derivative_rodeo/errors.rb
- lib/derivative_rodeo/generators/pdf_split_generator.rb
- lib/derivative_rodeo/generators/word_coordinates_generator.rb
- lib/derivative_rodeo/storage_locations/s3_location.rb
This commit includes 3 changes:
1. Replacing a misspelled name with the correct name
2. Improving logging
3. Adding a parameter to an exception.
At one point we had a method `globbed_tail_locations` however with some refactoring I renamed that to `matching_locations_in_file_dir`; however I missed the `globbed_tail_loations`.
In addition to fixing the misnamed method name, I'm adding some improved logging that helps with a problem I've encountered.  Namely that I got a
`#<ArgumentError: invalid byte sequence in UTF-8>` on a string.  That string was the contents of the file found at the `path_to_hocr`; however the exception didn't provide insight into the filename.
With this change, I fix a method that was broken and improve logging.
Last, the exception for buckets used an unprovided …
> 🐛 Fixing incorrect method name

- lib/derivative_rodeo/generators/base_generator.rb
- lib/derivative_rodeo/generators/pdf_split_generator.rb
Prior to this commit the `preprocessed_location_template` was the original PDF's location (as in "s3://bucket/aark_id/filename.ARCHIVAL.pdf"). This is because the calling of the generator has one file (e.g. the PDF) and multipe output files (e.g. the pages of the PDF).
What we ideally want is for the `preprocessed_location_template` to handle pages.  To know what page we're on requires knowledge of the `input_location`, and the convention that each "page" ends with the suffix `--page-NUMBER.EXTENSION`.
With this commit, we provide a crease for coercing the template into a page specific format.  If we don't have this change, then we end up using the `filename.ARCHIVAL.pdf` as the "tiff" for each of the pages. This results in very odd behavior, very much unexpected.
Related to:
- …
> 🐛 Correcting preprocessed_location_template for PDF

- lib/derivative_rodeo/generators/base_generator.rb
- spec/derivative_rodeo/generators/base_generator_spec.rb
The following user-story reflects the desired behavior:
```gherkin
Given an input uri
When I call #generated_files
Then there will exist a corresponding file at the template-derived output location
```
Prior to this commit, if a file did not exist at the output location but did exist at the pre-processed location, we would return the pre-processed location (which existed).
However, the goal of the `#generated_files` method was to ensure that there were files at the output location based on the input URIs and the output and pre-processed templates.
With this commit, we have a scenario
```gherkin
Given an input uri
And a corresponding template-derived output location that does not exist
And a corresponding template-derived preprocessed location that does exist
When I call #generated_files …
```
> 🐛 Copying pre-processed files to output location

- lib/derivative_rodeo/errors.rb
- lib/derivative_rodeo/storage_locations/concerns/download_concern.rb
- lib/derivative_rodeo/storage_locations/file_location.rb
- lib/derivative_rodeo/storage_locations/s3_location.rb
Prior to this commit many of the FileMissingError had no context of what
file was missing.
With this commit we can see more specific details of what's missing and
hopefully provide better insight into the specific file failure.
> 🧹 Add nuanced logging for FileMissingError

- lib/derivative_rodeo/storage_locations/concerns/download_concern.rb
- spec/derivative_rodeo/storage_locations/http_location_spec.rb
- spec/derivative_rodeo/storage_locations/https_location_spec.rb
In working towards gracefully handling a failed copy of a resource in
SpaceStone, we conditionally updated the `preprocess_template_location` to
be the original HTTP(s) location.  The idea being that if it does not
exist in the pre-processed location
The
[DerivativeRodeo::Generators::PdfSplitGenerator](https://github.com/scientist-softserv/derivative_rodeo/blob/84aa08e8387f105488a2b1a1e3821abacff4ad64/lib/derivative_rodeo/generators/pdf_split_generator.rb#L70-L80)
method (see below) can gracefully handle returning an empty list of
output locations.
```ruby
def existing_page_locations(input_location:)
tail_regexp = %r{#{input_location.file_basename}--page-\d+\.#{output_extension}$}
output_locations = input_location.derived_file_from(template: …
```
> 🐛 Add missing `#matching_locations_in_file_dir` method
